name = "irc"
main = "cms-site/worker/index.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./cms-site/public"
not_found_handling = "single-page-application"
run_worker_first = true
binding = "ASSETS"

# Secrets (usá wrangler secret put):
# wrangler secret put GITHUB_TOKEN
# wrangler secret put ADMIN_PASSWORD
